spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Gawlik81
    platform: postgresql
#  mandatory-file-encoding: ISO-8859-2
  http:
    encoding:
      charset: ISO-8859-2
      enabled: true
reprezentant:
  path: d:/baza.csv
server:
  port: 9000

